workflows:
  lunarae:
    name: LunaRae

    environment:
      flutter: stable
      xcode: 16.4

      vars:
        FLUTTER_TARGET: lib/main.dart
        XCODE_PROJECT: ios/Runner.xcodeproj
        XCODE_WORKSPACE: ios/Runner.xcworkspace
        XCODE_SCHEME: Runner

      groups:
        - app_store_credentials
        - google_play
        - keystore_credentials

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build Android App Bundle
        script: |
          flutter build appbundle \
            --release \
            --flavor android-production \
            -t lib/main.dart \
            --dart-define=OPENAI_API_KEY=$OPENAI_API_KEY

      - name: Build iOS IPA
        script: |
          flutter build ipa \
            --release \
            --dart-define=OPENAI_API_KEY=$OPENAI_API_KEY

    artifacts:
      - build/**/outputs/**/*.aab
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key:
          key_id: $APP_STORE_CONNECT_KEY_ID
          issuer_id: $APP_STORE_CONNECT_ISSUER_ID
          private_key: $APP_STORE_CONNECT_PRIVATE_KEY

      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
