workflows:
  lunarae:
    name: LunaRae

    environment:
      flutter: stable
      xcode: 16.4

      vars:
        FLUTTER_TARGET: lib/main.dart
        XCODE_PROJECT: ios/Runner.xcodeproj
        XCODE_WORKSPACE: ios/Runner.xcworkspace
        XCODE_SCHEME: Runner

      groups:
        - secrets

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build Android App Bundle
        script: |
          flutter build appbundle --release -t lib/main.dart

      - name: Build iOS IPA
        script: |
          flutter build ipa \
            --release \
            --dart-define=OPENAI_API_KEY=$OPENAI_API_KEY

    artifacts:
      - build/**/outputs/**/*.aab
      - build/ios/ipa/*.ipa
